import { v4 as uuidv4 } from "uuid";
import type { Exercise } from "./db";

export const DEFAULT_EXERCISES: Omit<Exercise, "id" | "createdAt" | "imageBlob">[] = [
  // ── CHEST ──────────────────────────────────────────────────────────────────
  {
    name: "Développé couché (Barre)",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "arms"],
    equipment: "barbell",
    instructions: "Allongé sur le banc, descendre la barre jusqu'à la poitrine puis pousser à la verticale.",
    isCustom: false,
  },
  {
    name: "Développé couché (Haltères)",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "arms"],
    equipment: "dumbbell",
    instructions: "Même mouvement qu'avec barre, amplitude plus large possible. Contrôler la descente.",
    isCustom: false,
  },
  {
    name: "Développé incliné (Barre)",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "arms"],
    equipment: "barbell",
    instructions: "Banc incliné à 30-45°. Cible le haut du pectoral.",
    isCustom: false,
  },
  {
    name: "Développé incliné (Haltères)",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "arms"],
    equipment: "dumbbell",
    instructions: "Banc incliné, haltères en pronation. Bonne amplitude en bas.",
    isCustom: false,
  },
  {
    name: "Écarté couché (Haltères)",
    muscleGroup: "chest",
    secondaryMuscles: [],
    equipment: "dumbbell",
    instructions: "Bras légèrement fléchis, descendre en arc de cercle jusqu'à ressentir l'étirement.",
    isCustom: false,
  },
  {
    name: "Écarté poulie haute (Cable)",
    muscleGroup: "chest",
    secondaryMuscles: [],
    equipment: "cable",
    instructions: "Poulies hautes, croiser les mains devant le bas-ventre. Isolé pour la définition.",
    isCustom: false,
  },
  {
    name: "Pompes",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "arms", "core"],
    equipment: "bodyweight",
    instructions: "Corps gainé, descendre jusqu'à frôler le sol, pousser fort en haut.",
    isCustom: false,
  },
  {
    name: "Dips (pectoraux)",
    muscleGroup: "chest",
    secondaryMuscles: ["arms", "shoulders"],
    equipment: "bodyweight",
    instructions: "Barres parallèles, se pencher légèrement en avant pour cibler les pecs. Descendre jusqu'à 90°.",
    isCustom: false,
  },

  // ── BACK ───────────────────────────────────────────────────────────────────
  {
    name: "Soulevé de terre",
    muscleGroup: "back",
    secondaryMuscles: ["legs", "core"],
    equipment: "barbell",
    instructions: "Pieds dans l'axe des hanches, dos droit, soulever la barre en gardant les épaules en arrière.",
    isCustom: false,
  },
  {
    name: "Tirage horizontal barre (Rowing)",
    muscleGroup: "back",
    secondaryMuscles: ["arms"],
    equipment: "barbell",
    instructions: "Dos à 45°, barre prise en pronation, tirer jusqu'au nombril. Serrer les omoplates.",
    isCustom: false,
  },
  {
    name: "Tirage horizontal haltère (Rowing 1 bras)",
    muscleGroup: "back",
    secondaryMuscles: ["arms"],
    equipment: "dumbbell",
    instructions: "Un genou sur le banc, tirer l'haltère jusqu'à la hanche. Garder le dos plat.",
    isCustom: false,
  },
  {
    name: "Tirage poulie basse (Cable Row)",
    muscleGroup: "back",
    secondaryMuscles: ["arms"],
    equipment: "cable",
    instructions: "Assis, tirer vers le bas du ventre, coudes proches du corps. Ne pas arrondir le dos.",
    isCustom: false,
  },
  {
    name: "Tirage vertical (Lat Pulldown)",
    muscleGroup: "back",
    secondaryMuscles: ["arms"],
    equipment: "cable",
    instructions: "Saisir la barre large, tirer jusqu'à la clavicule. Se pencher légèrement en arrière.",
    isCustom: false,
  },
  {
    name: "Tractions (Pull-ups)",
    muscleGroup: "back",
    secondaryMuscles: ["arms"],
    equipment: "bodyweight",
    instructions: "Prise pronation, tirer le menton au-dessus de la barre. Contrôler la descente.",
    isCustom: false,
  },
  {
    name: "Chin-ups (Supination)",
    muscleGroup: "back",
    secondaryMuscles: ["arms"],
    equipment: "bodyweight",
    instructions: "Prise supination, engager davantage le biceps. Monter le menton au-dessus de la barre.",
    isCustom: false,
  },
  {
    name: "Tirage nuque machine",
    muscleGroup: "back",
    secondaryMuscles: ["arms"],
    equipment: "machine",
    instructions: "Barre tirée derrière la tête à hauteur des trapèzes. Attention à la nuque.",
    isCustom: false,
  },

  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  {
    name: "Développé militaire (Barre)",
    muscleGroup: "shoulders",
    secondaryMuscles: ["arms", "core"],
    equipment: "barbell",
    instructions: "Barre au niveau du menton, pousser à la verticale au-dessus de la tête. Gainage obligatoire.",
    isCustom: false,
  },
  {
    name: "Développé épaules (Haltères)",
    muscleGroup: "shoulders",
    secondaryMuscles: ["arms"],
    equipment: "dumbbell",
    instructions: "Haltères à hauteur des épaules, pousser vers le haut sans bloquer les coudes.",
    isCustom: false,
  },
  {
    name: "Élévations latérales (Haltères)",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "dumbbell",
    instructions: "Monter les haltères jusqu'à l'horizontale, légère flexion des coudes. Contrôler la descente.",
    isCustom: false,
  },
  {
    name: "Élévations latérales (Cable)",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "cable",
    instructions: "Tension constante tout au long du mouvement. Idéal pour le faisceau latéral.",
    isCustom: false,
  },
  {
    name: "Oiseau (Élévations postérieures)",
    muscleGroup: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "dumbbell",
    instructions: "Penché en avant, bras légèrement fléchis, lever les haltères sur les côtés. Cibler le deltoïde postérieur.",
    isCustom: false,
  },
  {
    name: "Face Pull (Cable)",
    muscleGroup: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "cable",
    instructions: "Corde à hauteur du front, tirer vers le visage en écartant les mains. Indispensable pour la santé des épaules.",
    isCustom: false,
  },
  {
    name: "Shrugs (Haussements d'épaules)",
    muscleGroup: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "barbell",
    instructions: "Monter les épaules vers les oreilles, maintenir 1 sec en haut. Cibler les trapèzes.",
    isCustom: false,
  },

  // ── LEGS ───────────────────────────────────────────────────────────────────
  {
    name: "Squat (Barre)",
    muscleGroup: "legs",
    secondaryMuscles: ["core", "back"],
    equipment: "barbell",
    instructions: "Pieds à largeur d'épaules, descendre jusqu'à ce que les cuisses soient parallèles au sol. Genoux dans l'axe des orteils.",
    isCustom: false,
  },
  {
    name: "Goblet Squat (Haltère)",
    muscleGroup: "legs",
    secondaryMuscles: ["core"],
    equipment: "dumbbell",
    instructions: "Haltère tenu au niveau de la poitrine, squatter profond. Bon exercice de transition.",
    isCustom: false,
  },
  {
    name: "Leg Press",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    instructions: "Pied haut et large = ischio-jambiers/fessiers. Pied bas et serré = quadriceps.",
    isCustom: false,
  },
  {
    name: "Fentes (Haltères)",
    muscleGroup: "legs",
    secondaryMuscles: ["core"],
    equipment: "dumbbell",
    instructions: "Grand pas en avant, genou arrière proche du sol. Garder le torse droit.",
    isCustom: false,
  },
  {
    name: "Romanian Deadlift (Haltères)",
    muscleGroup: "legs",
    secondaryMuscles: ["back"],
    equipment: "dumbbell",
    instructions: "Jambes quasi-tendues, descendre les haltères le long des jambes jusqu'à l'étirement des ischio. Dos plat.",
    isCustom: false,
  },
  {
    name: "Romanian Deadlift (Barre)",
    muscleGroup: "legs",
    secondaryMuscles: ["back"],
    equipment: "barbell",
    instructions: "Même mouvement avec barre. Charge plus importante possible.",
    isCustom: false,
  },
  {
    name: "Leg Curl (Machine)",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    instructions: "Allongé face contre le siège, ramener les talons vers les fessiers. Contrôler la phase excentrique.",
    isCustom: false,
  },
  {
    name: "Leg Extension (Machine)",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    instructions: "Assis, étendre les jambes à la verticale. Maintenir 1 sec en haut. Quadriceps uniquement.",
    isCustom: false,
  },
  {
    name: "Hip Thrust (Barre)",
    muscleGroup: "legs",
    secondaryMuscles: ["core"],
    equipment: "barbell",
    instructions: "Dos appuyé sur un banc, barre sur les hanches, pousser les hanches vers le plafond. Fessiers ++.",
    isCustom: false,
  },
  {
    name: "Mollets debout (Machine)",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    instructions: "Monter sur la pointe des pieds, maintenir 1 sec. Descendre lentement pour l'étirement complet.",
    isCustom: false,
  },
  {
    name: "Hack Squat (Machine)",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    instructions: "Pieds en bas de la plateforme pour cibler les quadriceps. Descendre jusqu'à 90°.",
    isCustom: false,
  },

  // ── ARMS ───────────────────────────────────────────────────────────────────
  {
    name: "Curl biceps (Barre EZ)",
    muscleGroup: "arms",
    secondaryMuscles: [],
    equipment: "barbell",
    instructions: "Coudes fixes le long du corps. Monter la barre jusqu'aux épaules, contrôler la descente.",
    isCustom: false,
  },
  {
    name: "Curl biceps (Haltères)",
    muscleGroup: "arms",
    secondaryMuscles: [],
    equipment: "dumbbell",
    instructions: "Alterner ou simultané. Supiner les poignets en montant pour un pic biceps maximum.",
    isCustom: false,
  },
  {
    name: "Curl marteau (Haltères)",
    muscleGroup: "arms",
    secondaryMuscles: [],
    equipment: "dumbbell",
    instructions: "Prise neutre (pouce vers le haut). Cible le brachial et l'avant-bras.",
    isCustom: false,
  },
  {
    name: "Curl poulie basse (Cable)",
    muscleGroup: "arms",
    secondaryMuscles: [],
    equipment: "cable",
    instructions: "Tension constante sur tout le mouvement. Idéal en fin de séance bras.",
    isCustom: false,
  },
  {
    name: "Extensions triceps (Barre EZ couché)",
    muscleGroup: "arms",
    secondaryMuscles: [],
    equipment: "barbell",
    instructions: "Allongé, descendre la barre vers le front ou derrière la tête. Coudes fixes.",
    isCustom: false,
  },
  {
    name: "Extensions triceps poulie haute",
    muscleGroup: "arms",
    secondaryMuscles: [],
    equipment: "cable",
    instructions: "Corde ou barre, coudes plaqués contre la tête, étendre les bras complètement.",
    isCustom: false,
  },
  {
    name: "Dips (triceps)",
    muscleGroup: "arms",
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "bodyweight",
    instructions: "Barres parallèles, corps vertical, coudes proches du corps. Descendre jusqu'à 90°.",
    isCustom: false,
  },
  {
    name: "Kickback triceps (Haltère)",
    muscleGroup: "arms",
    secondaryMuscles: [],
    equipment: "dumbbell",
    instructions: "Dos à plat, coude en arrière fixe, étendre le bras en arrière. Maintenir en haut.",
    isCustom: false,
  },

  // ── CORE ───────────────────────────────────────────────────────────────────
  {
    name: "Planche (Plank)",
    muscleGroup: "core",
    secondaryMuscles: ["shoulders"],
    equipment: "bodyweight",
    instructions: "Corps aligné de la tête aux talons. Contracter les abdos, fesses et quadriceps. Tenir la position.",
    isCustom: false,
  },
  {
    name: "Crunch",
    muscleGroup: "core",
    secondaryMuscles: [],
    equipment: "bodyweight",
    instructions: "Mains derrière la tête, contracter les abdominaux pour décoller les épaules du sol. Ne pas tirer sur la nuque.",
    isCustom: false,
  },
  {
    name: "Relevé de jambes suspendu",
    muscleGroup: "core",
    secondaryMuscles: [],
    equipment: "bodyweight",
    instructions: "Suspendu à une barre, monter les jambes tendues jusqu'à l'horizontale. Contrôler la descente.",
    isCustom: false,
  },
  {
    name: "Ab Wheel (Rouleau abdominal)",
    muscleGroup: "core",
    secondaryMuscles: ["shoulders", "back"],
    equipment: "other",
    instructions: "À genoux, dérouler le rouleau aussi loin que possible sans creuser le dos. Revenir lentement.",
    isCustom: false,
  },
  {
    name: "Russian Twist",
    muscleGroup: "core",
    secondaryMuscles: [],
    equipment: "bodyweight",
    instructions: "Assis à 45°, pieds décollés. Tourner le buste de gauche à droite. Ajouter une charge pour progresser.",
    isCustom: false,
  },

  // ── FULL BODY / CARDIO ─────────────────────────────────────────────────────
  {
    name: "Burpees",
    muscleGroup: "full_body",
    secondaryMuscles: ["chest", "legs", "core"],
    equipment: "bodyweight",
    instructions: "Debout → squat → pompe → squat → saut. Enchaîner sans pause.",
    isCustom: false,
  },
  {
    name: "Kettlebell Swing",
    muscleGroup: "full_body",
    secondaryMuscles: ["legs", "back", "core"],
    equipment: "kettlebell",
    instructions: "Hanches comme moteur, pas les bras. Projeter le kettlebell jusqu'aux épaules par extension des hanches.",
    isCustom: false,
  },
  {
    name: "Turkish Get-Up",
    muscleGroup: "full_body",
    secondaryMuscles: ["shoulders", "core", "legs"],
    equipment: "kettlebell",
    instructions: "Passer de la position allongée à debout avec le kettlebell bras tendu. Mouvement complet en 7 étapes.",
    isCustom: false,
  },
];

export function buildSeedExercises(): Exercise[] {
  return DEFAULT_EXERCISES.map((e) => ({
    ...e,
    id: uuidv4(),
    imageBlob: null,
    createdAt: new Date(),
  }));
}
